### ISSUE TITLE
Training Detail

### ISSUE THREAD

**Issue by yuta-tech** [daerduoCarey/pt2pc#1]
Dear Sir  
I'm interested in your paper. So I want to reproduce the result.  
And then I have some question about training detail.  

1. How many epoch or iteration do you train model?  and How long does it takes?
2. What GPU do you use?  

I'd appreciate it if you could reply to me.

**Comment by daerduoCarey** [comment]
You can train the nets until the Wasserstein distances converge (training on different categories requires different epoches). The GPU doesn't matter.

**Comment by yuta-tech** [comment]
Thank you for replying. I understand.   
I am looking forward to more code.  
Thank you.
