### ISSUE TITLE
Pretrained models / sample generation script?

### ISSUE THREAD

**Issue by djr2015** [daerduoCarey/pt2pc#2]
Thanks for your work and this codebase! 

Would it be possible to upload an already-trained model and some brief script for using the generator to generate a set of outputs given a part tree?

**Comment by daerduoCarey** [comment]
Please check https://github.com/daerduoCarey/pt2pc#quick-start. I've added the pretrained models and a simple Jupyter Notebook for result visualization.

Let me know if you need more helps. Thanks!
