### ISSUE TITLE
Torch-scatter + Torch version conflict

### ISSUE THREAD

**Issue by AlexanderRayCarlson** [daerduoCarey/pt2pc#3]
Hello, I am trying to set up this code to evaluate for an experiment. Torch 1.1.0 is listed, but torch-scatter download only goes as low as 1.4.0 compatible now. 

I installed 1.4.0 but end up getting errors with setup.py afterwards.

Is there a currently supported combination of Torch and Torch-scatter for this project?

**Comment by daerduoCarey** [comment]
Thanks for the question. It seems that this codebase doesn't require torch-scatter at all. Sorry for the confusion.
